name: Draconian Code Formatting

# This action works with pull requests and pushes
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Code-Styling:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Prettify code
      uses: creyD/prettier_action@v3.1
      with:
        prettier_options: --write **/*.{js,md}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
