on:
  workflow_dispatch:
  schedule:
  - cron: 0 0 * * 3
name: Update Packages
jobs:
  package-update:
    runs-on: ubuntu-latest
    steps:
    - name: package-update
      uses: taichi/actions-package-update@master
      env:
       AUTHOR_EMAIL: realkoolisw@gmail.com
       AUTHOR_NAME: Koolisw
       EXECUTE: "true"
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       UPDATE_COMMAND: npm
      with:
       args: update
